name: Auto Label PRs by Commit Type

on:
  pull_request:
    types: [ opened, synchronize, reopened ]

jobs:
  label:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Ensure full git history is available
        run: |
          if git rev-parse --is-shallow-repository | grep -q true; then
            git fetch --prune --unshallow --tags origin +refs/heads/*:refs/remotes/origin/*
          else
            git fetch --prune --tags origin +refs/heads/*:refs/remotes/origin/*
          fi

      - name: Get commits from PR
        id: commits
        run: |
          types=$(git log origin/main..HEAD --pretty=format:%s | grep -Eo '^(feat|fix|chore|docs|refactor)' | sort -u)
          echo "Found commit types: $types"
          labels=$(printf '%s\n' $types | jq -R . | jq -s .)

          echo "LABELS<<EOF" >> $GITHUB_OUTPUT
          echo "$labels" >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT

      - name: Apply label
        uses: actions-ecosystem/action-add-labels@v1
        if: steps.label.outputs.LABELS != ''
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          labels: ${{ steps.label.outputs.LABELS }}

