name: Auto Label PRs by Commit Type

on:
  pull_request:
    types: [ opened, synchronize, reopened ]

jobs:
  label:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Fetch full git history
        run: git fetch --prune --unshallow --tags origin +refs/heads/*:refs/remotes/origin/*

      - name: Get commit types from PR
        id: commits
        run: |
          types=$(git log origin/main..HEAD --pretty=format:%s | grep -Eo '^(feat|fix|chore|docs|refactor)' | sort | uniq | tr '\n' ' ')
          echo "Found commit types: $types"
          echo "COMMIT_TYPES=$types" >> $GITHUB_OUTPUT

      - name: Determine labels to apply
        id: labels
        run: |
          types="${{ steps.commits.outputs.COMMIT_TYPES }}"
          labels=""

          for type in feat fix chore docs refactor; do
            if echo "$types" | grep -q "$type"; then
              labels="$labels,$type"
            fi
          done

          # Remove leading comma
          labels="${labels#,}"
          echo "Applying labels: $labels"
          echo "LABELS=$labels" >> $GITHUB_OUTPUT

      - name: Apply labels
        if: steps.labels.outputs.LABELS != ''
        uses: actions-ecosystem/action-add-labels@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          labels: ${{ steps.labels.outputs.LABELS }}
