name: Auto Label PRs

on:
  pull_request:
    types: [opened]

jobs:
  add-label:
    runs-on: ubuntu-latest
    steps:
      - name: Label by branch prefix
        uses: actions-ecosystem/action-add-labels@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          labels: |
            feat: ^feat/
            fix: ^fix/
            chore: ^chore/
            docs: ^docs/
            refactor: ^refactor/
